<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>genius-agent-ident-123</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5" />
		<PackageReference Include="Scalar.AspNetCore" Version="2.13.17" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\GeniusAgent.Application\GeniusAgent.Application.csproj" />
	  <ProjectReference Include="..\GeniusAgent.Core\GeniusAgent.Core.csproj" />
	  <ProjectReference Include="..\GeniusAgent.Infrastructure\GeniusAgent.Infrastructure.csproj" />
	</ItemGroup>

</Project>